# 🧩 Ejemplo de clase: Condicionales en Python (sin bucles ni funciones)
En este notebook practicamos condicionales (`if`, `elif`, `else`) sobre **listas, tuplas, diccionarios** y **DataFrames**, y vemos comparaciones vectorizadas con `.loc[]` y `np.where()`.

In [7]:
import pandas as pd # type: ignore

ModuleNotFoundError: No module named 'pandas'

In [8]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 23.7 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 46.0 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.4 pandas-3.0.2

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd

In [10]:
datos = pd.read_csv("../data/muestras_calidad_agua.csv")

In [11]:
datos.head()

                          sitio   pH  oxigeno  temperatura
0                Río Subachoque  7.2      7.8         18.5
1   Quebrada Honda (Facatativá)  6.3      6.2         19.4
2          Río Botello (Madrid)  6.8      5.9         22.7
3  Afluente San José (El Rosal)  7.9      8.3         20.1
4                   Río Villeta  8.7      6.1         28.3

In [12]:
# Información general del DataFrame
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sitio        10 non-null     str
 1   pH           10 non-null     float64
 2   oxigeno      10 non-null     float64
 3   temperatura  10 non-null     float64
dtypes: float64(3), str(1)
memory usage: 452.0 bytes

In [13]:
# Estadísticas descriptivas
datos.describe()

              pH    oxigeno  temperatura
count  10.000000  10.000000    10.000000
mean    7.190000   6.250000    24.360000
std     0.933869   1.237605     4.092323
min     5.900000   4.500000    18.500000
25%     6.425000   5.375000    20.750000
50%     7.300000   6.150000    24.800000
75%     7.825000   6.925000    27.425000
max     8.700000   8.300000    30.500000

In [19]:
for columna in datos.columns:
    print(columna)

sitio
pH
oxigeno
temperatura

In [20]:
# =========================================
# Cantidad de filas y columnas
# =========================================

print("Dimensiones del DataFrame:")
print(datos.shape)

Dimensiones del DataFrame:
(10, 4)

In [21]:
# =========================================
# Valores nulos por columna
# =========================================

tabla_nulos = datos.isnull().sum().reset_index()

tabla_nulos.columns = ["Columna", "Valores nulos"]

tabla_nulos

       Columna  Valores nulos
0        sitio              0
1           pH              0
2      oxigeno              0
3  temperatura              0

In [22]:
# =========================================
# Estadísticas descriptivas más organizadas
# =========================================

estadisticas = datos.describe()

estadisticas

              pH    oxigeno  temperatura
count  10.000000  10.000000    10.000000
mean    7.190000   6.250000    24.360000
std     0.933869   1.237605     4.092323
min     5.900000   4.500000    18.500000
25%     6.425000   5.375000    20.750000
50%     7.300000   6.150000    24.800000
75%     7.825000   6.925000    27.425000
max     8.700000   8.300000    30.500000

In [23]:
# =========================================
# Promedio de variables numéricas
# =========================================

promedios = datos.mean(numeric_only=True).reset_index()

promedios.columns = ["Variable", "Promedio"]

promedios

      Variable  Promedio
0           pH      7.19
1      oxigeno      6.25
2  temperatura     24.36

In [24]:
# =========================================
# Valores mínimos
# =========================================

minimos = datos.min(numeric_only=True).reset_index()

minimos.columns = ["Variable", "Valor mínimo"]

minimos

      Variable  Valor mínimo
0           pH           5.9
1      oxigeno           4.5
2  temperatura          18.5

In [25]:
# =========================================
# Valores máximos
# =========================================

maximos = datos.max(numeric_only=True).reset_index()

maximos.columns = ["Variable", "Valor máximo"]

maximos

      Variable  Valor máximo
0           pH           8.7
1      oxigeno           8.3
2  temperatura          30.5

In [26]:
# =========================================
# Evaluación del pH promedio
# =========================================

promedio_ph = datos["pH"].mean()

print(f"Promedio de pH: {promedio_ph:.2f}")

if promedio_ph > 7:
    print("El agua tiende a ser básica")
elif promedio_ph == 7:
    print("El agua es neutra")
else:
    print("El agua tiende a ser ácida")

Promedio de pH: 7.19
El agua tiende a ser básica

In [33]:
# =========================================
# Evaluación de temperatura
# =========================================

promedio_temperatura = datos["temperatura"].mean()

print(f"Promedio de temperatura: {promedio_temperatura:.2f} °C")

if promedio_temperatura > 25:
    print("La temperatura del agua es alta")
else:
    print("La temperatura del agua es normal")

Promedio de temperatura: 24.36 °C
La temperatura del agua es normal

In [34]:
# =========================================
# Visualización completa del DataFrame
# =========================================

datos

                           sitio   pH  oxigeno  temperatura
0                 Río Subachoque  7.2      7.8         18.5
1    Quebrada Honda (Facatativá)  6.3      6.2         19.4
2           Río Botello (Madrid)  6.8      5.9         22.7
3   Afluente San José (El Rosal)  7.9      8.3         20.1
4                    Río Villeta  8.7      6.1         28.3
5  Quebrada Cune (San Francisco)  6.0      4.5         25.2
6            Río Tobia (Nocaima)  7.4      5.2         26.9
7       Quebrada Negra (La Vega)  7.6      7.0         24.4
8          Río Bahamón (Sasaima)  8.1      6.7         27.6
9        Río Guayuriba (La Mesa)  5.9      4.8         30.5